export const CHANGE_USERADDR = 'MUT_CHANGE_USERADDR'
export const CHANGE_LANGUAGE = 'MUT_CHANGE_LANGUAGE'
export const CHANGE_BAMBOO_COUNT = 'MUT_CHANGE_BAMBOO_COUNT'
export const CHANGE_USER_LOCATION = 'MUT_CHANGE_USER_LOCATION'