
const statusCodes = {
	'en': {
		'CommonCodes_Service_Wrong': 'service is busy, please try again!',
		'CommonCodes_Params_Check_Fail': 'params check fail!',
		'CommonCodes_Request_Method_Wrong': 'request method wrong!',
		'CommonCodes_Response_Succ': 'Response successful!',
		'CommonCodes_Token_Fail': 'token fail',
		'CommonCodes_No_Access': 'permission denied',
		'CommonCodes_Assets_Not_Enought': 'Not Enought Asset!',
		'LoginCodes_Email_Exist': 'your address is registered!',
		'LoginCodes_Email_Already_Exist': 'your email is registered!',
	  'LoginCodes_Login_DataWrong': 'address or password is incorrectly!',
	  'LoginCodes_Login_Succ': 'login successful',
	  'LoginCodes_Login_No_Account': 'please register first',
	  'LoginCodes_Login_IllegalData': 'ddress or password is incorrectly!',
	  'LoginCodes_Password_Not_Repeat': 'password repeat should the same',
	  'LoginCodes_Register_Failed': 'register failed',
	  'LoginCodes_Register_Succ': 'register success',
	  'LoginCodes_Params_Check_Fail': 'params check fail',
	  'LoginCodes_Mail_Send_Succ': 'email send success!',
	  'LoginCodes_Mail_Send_Error': 'failed to send email, please try later',
	  'LoginCodes_User_Not_Bind_Email': 'please bind email first',
	  'LoginCodes_Query_Email_Succ': 'query user email success',
	  'LoginCodes_Bind_Email_Fail': 'Bind Email Failed, Please Try Later！',
	  'LoginCodes_Code_Error': 'code wrong',
	  'LoginCodes_Code_Correct': 'code correct',
	  'LoginCodes_Reset_Pass_Succ': 'reset password successful',
	  'LoginCodes_Token_Fail': 'token failed',
	  'LoginCodes_Get_User_Info': 'get user info successful',
	  'LoginCodes_Change_Login_Pwd_Succ': 'change login password successful',
	  'LoginCodes_Change_Trade_Pwd_Succ': 'change trade password successful',
	  'LoginCodes_Change_Login_Pwd_Fail': 'failed to change login password',
	  'LoginCodes_Change_Trade_Pwd_Fail': 'failed to change trade password',
	  'LoginCodes_Assets_Data_Normal': 'get my assets successful',
	  'LoginCodes_Assets_Data_Null': 'failed to get my assets',
	  'LoginCodes_Trade_Pwd_Wrong': 'trade password wrong',
	  'LoginCodes_Get_User_Bamboo': 'get user bamboo successful',
	  'LoginCodes_Get_Combo_Data_Fail': 'failed to get hash data',
	  'Copy_Addr_Succ': 'address copy successful',
  	'Copy_Addr_Fail': 'failed to copy address',
	  'AssetsCodes_Assets_Data_Normal': 'get assets data successful',
		'AssetsCodes_Assets_Data_Null': 'failed to get assets data',
		'AssetsCodes_Assets_Null': 'assets is empty',
		'PandaOwnerCodes_Query_Panda_Info_Normal': 'query wuno info successful',
		'PandaOwnerCodes_Already_Gene_Free_Panda': 'already have a wuno',
		'PandaOwnerCodes_Gene_Free_Panda_Succ': 'generate wuno successful',
		'PandaOwnerCodes_Query_Panda_By_Addr': 'query all wunos',
		'PandaOwnerCodes_Query_Panda_In_Sold': 'query all sold wunos ',
		'PandaOwnerCodes_Not_Out_Panda': 'user not having out wuno',
		'PandaOwnerCodes_More_Than_Max_Panda': 'Max Wuno Is 3!',
		'LandProductCodes_Get_Star_Point_Succ': 'get product center successful',
		'LandProductCodes_Get_Star_Point_Fail': 'failed to query product center',
		'LandProductCodes_Get_Prepare_Product_Fail': 'failed to get voted goods',
		'LandProductCodes_Get_Prepare_Product_Succ': 'get voted goods successful',
		'LandProductCodes_Sell_Product_Fail': 'fail to sell goods',
		'LandProductCodes_Drop_Product_Fail': 'fail to drop goods',
		'LandProductCodes_Del_Product_Fail': 'fail to delete goods!',
		'LandProductCodes_User_No_Such_Product': 'user have not full fragment',
		'LandProductCodes_Query_Product_Fail': 'failed to query specific product ',
		'LandProductCodes_Insert_Product_Fail': 'fail to insert product',
		'LandProductCodes_Update_Product_Fail': 'fail to update user product',
		'LandProductCodes_User_Product_Null': 'user goods is empty',
		'LandProductCodes_User_Product_Not_Null': 'user goods is not empty',
		'LandProductCodes_Vote_Product_Succ': 'vote product successful',
		'LandProductCodes_Vote_Product_Fail': 'fail to vote product',
		'LandProductCodes_Get_Current_Product_Succ': 'get current product successful',
		'LandProductCodes_Get_Current_Product_Fail':'fail to get current product',
		'LandProductCodes_Update_User_Bamboo_Succ': 'update user bamboo',
		'LandProductCodes_Exchange_Product_Succ': 'product echange successful',
		'PandaLandCodes_No_Such_Panda': 'no such wuno',
		'PandaLandCodes_No_More_Bamboo_For_Out': 'no enough bamboo',
		'PandaLandCodes_No_Product_In_Land': 'no product in search',
		'PandaLandCodes_Update_Panda_Attr_Fail': 'fail to update wuno attribute',
		'PandaLandCodes_Update_Land_Assets_Fail': 'fail to update user assets',
		'PandaLandCodes_Back_Assets_Carry_Fail': 'fail to carry back assets',
		'PandaLandCodes_Back_Assets_Carry_Empty': 'Master, wuno find nothing!',
		'PandaLandCodes_Delete_Back_Assets_Fail': 'fail to delete back assets',
		'PandaLandCodes_Panda_Out_Succ': 'start out successful',
		'PandaLandCodes_Panda_Not_Sold': 'wuno is unsold',
		'PandaLandCodes_Sell_Panda_Succ': 'sell wuno successful',
		'PandaLandCodes_Unsell_Panda_Succ': 'unsold wuno successful',
		'PandaLandCodes_Only_One_Unsold_Panda': 'at least one unsold wuno!',
		'PandaLandCodes_Buy_Panda_Fail': 'fail to buy wuno',
		'PandaLandCodes_Buy_Panda_Succ': 'buy wuno successful',
		'PandaLandCodes_Back_Assets_Carry_Succ': 'carry back successful',
		'PandaLandCodes_Drop_Panda_Fail': 'drop wuno successful!',
		'PandaLandCodes_Panda_Sire_Succ': 'sire wuno successful',
		'Exchange_Product_Info_Not_Null': 'product exchange info is not null!',
		'JoiCodes_Addr_Illegal': 'address is illegal',
		'JoiCodes_Gen_Illegal': 'wuno geni is illegal',
		'JoiCodes_Attr_Illegal': 'wuno attribute is illegal',
		'JoiCodes_Price_Illegal': 'price is illegal',
		'JoiCodes_Email_Illegal': 'email is illegal',
		'JoiCodes_Pwd_Illegal': 'password is illegal',
		'JoiCodes_State_Illegal': 'state is illegal',
		'JoiCodes_Titude_Illegal': 'longititu or latitude is illegal',
		'JoiCodes_ProductAttr_Illegal': 'product attribute is illegal',
		'JoiCodes_Dir_Illegal': 'direction is illegal',
		'JoiCodes_ProductId_Illegal': 'productId is illegal',
		'JoiCodes_Phone_Illegal': 'phone number is illegal',
		'Insufficient_Bamboo_Balance': 'Insufficient Bamboo Balance!',
		'Information_Not_Completed': 'Please Fill All Need Information!',
		'LandProductCodes_Roll_Out_Succ': 'Assets Withdraw successful!',
		'Recharge_Info_Not_Null': 'Recharge Information Not null!',
		'Recharge_Assets_Succ': 'Recharge Order Create successful!',
		'At_Least_50_Bamboo_For_Out': 'At Least 50 Bamboo For Out!',
		'Vote_Experied': 'Voting is Not Starting Or Experied!'
	},
	'cn': {
		'CommonCodes_Service_Wrong': '服务器忙，请稍后再试',
		'CommonCodes_Params_Check_Fail': '参数校验失败',
		'CommonCodes_Request_Method_Wrong': '请求方式错误！',
		'CommonCodes_Response_Succ': '成功返回！',
		'CommonCodes_Token_Fail': 'Token失效',
		'CommonCodes_No_Access': '没有权限',
		'CommonCodes_Assets_Not_Enought': '资产不足!',
		'LoginCodes_Email_Exist': '你的账号已经注册了！', // TODO
		'LoginCodes_Email_Already_Exist': '你的邮件已经被注册过！',
	  'LoginCodes_Login_DataWrong': '账号密码输入错误',
	  'LoginCodes_Login_Succ': '登陆成功',
	  'LoginCodes_Login_No_Account': '请先注册',
	  'LoginCodes_Login_IllegalData': '账号密码输入错误',
	  'LoginCodes_Password_Not_Repeat': '新密码设置应该一样！',
	  'LoginCodes_Register_Failed': '注册失败，请稍后再试',
	  'LoginCodes_Register_Succ': '注册成功',
	  'LoginCodes_Params_Check_Fail': '参数校验失败',
	  'LoginCodes_Mail_Send_Succ': '邮件发送成功！',
	  'LoginCodes_Mail_Send_Error': '邮件发送失败,请稍后再试',
	  'LoginCodes_User_Not_Bind_Email': '用户未绑定邮箱',
	  'LoginCodes_Query_Email_Succ': '查询用户邮箱成功！',
	  'LoginCodes_Bind_Email_Fail': '绑定邮箱失败, 请稍后再试！',
	  'LoginCodes_Code_Error': '验证码错误！',
	  'LoginCodes_Code_Correct': '验证码正确！',
	  'LoginCodes_Reset_Pass_Succ': '重置密码成功！',
	  'LoginCodes_Token_Fail': 'Token失效',
	  'LoginCodes_Get_User_Info': '获取用户信息成功！',
	  'LoginCodes_Change_Login_Pwd_Succ': '更改登陆密码成功！',
	  'LoginCodes_Change_Trade_Pwd_Succ': '更改交易密码成功',
	  'LoginCodes_Change_Login_Pwd_Fail': '更改登陆密码失败，请稍后再试！',
	  'LoginCodes_Change_Trade_Pwd_Fail': '更改交易密码失败，请稍后再试！',
	  'LoginCodes_Assets_Data_Normal': '资产数据返回正常！',
	  'LoginCodes_Assets_Data_Null': '资产数据返回错误！',
	  'LoginCodes_Trade_Pwd_Wrong': '交易密码不正确！',
	  'LoginCodes_Get_User_Bamboo': '获取用户参与挖矿得到的bamboo数量成功！',
	  'LoginCodes_Get_Combo_Data_Fail': '获取coinhive数据失败！',
	  'Copy_Addr_Succ': '地址复制成功！',
  	'Copy_Addr_Fail': '地址复制失败',
	  'AssetsCodes_Assets_Data_Normal': '资产数据返回正常！',
		'AssetsCodes_Assets_Data_Null': '资产数据返回错误！',
		'AssetsCodes_Assets_Null': '资产价值为空',
		'PandaOwnerCodes_Query_Panda_Info_Normal': '查询呜喏信息成功！',
		'PandaOwnerCodes_Already_Gene_Free_Panda': '已经生成过一只G10的呜喏',
		'PandaOwnerCodes_Gene_Free_Panda_Succ': '生成G10呜喏成功',
		'PandaOwnerCodes_Query_Panda_By_Addr': '查询地址下所有呜喏成功！',
		'PandaOwnerCodes_Query_Panda_In_Sold': '查询所有在售是呜喏！',
		'PandaOwnerCodes_Not_Out_Panda': '该用户没有外出的呜喏',
		'PandaOwnerCodes_More_Than_Max_Panda': '用户所拥有呜喏不能超过三只！',
		'LandProductCodes_Get_Star_Point_Succ': '得到商品产生中心成功！',
		'LandProductCodes_Get_Star_Point_Fail': '商品中心获取失败',
		'LandProductCodes_Get_Prepare_Product_Fail': '获取投票中的商品失败！',
		'LandProductCodes_Get_Prepare_Product_Succ': '获取投票中的商品成功！',
		'LandProductCodes_Sell_Product_Fail': '出售商品失败！',
		'LandProductCodes_Drop_Product_Fail': '下架商品失败',
		'LandProductCodes_Del_Product_Fail': '删除商品失败!',
		'LandProductCodes_User_No_Such_Product': '用户未集齐当前商品碎片！',
		'LandProductCodes_Query_Product_Fail': '查询用户指定商品失败！',
		'LandProductCodes_Insert_Product_Fail': '插入用户商品失败',
		'LandProductCodes_Update_Product_Fail': '更新用户商品失败',
		'LandProductCodes_User_Product_Null': '用户的商品为空！',
		'LandProductCodes_User_Product_Not_Null': '用户的商品不为空！',
		'LandProductCodes_Vote_Product_Succ': '商品投票成功！',
		'LandProductCodes_Vote_Product_Fail': '商品投票失败！',
		'LandProductCodes_Get_Current_Product_Succ': '获取当前商品成功！',
		'LandProductCodes_Get_Current_Product_Fail':'获取当前商品失败！',
		'LandProductCodes_Update_User_Bamboo_Succ': '更新用户的竹子数量成功！',
		'LandProductCodes_Exchange_Product_Succ': '商品兑换成功！',
		'PandaLandCodes_No_Such_Panda': '没有这只呜喏',
		'PandaLandCodes_No_More_Bamboo_For_Out': '没有足够的竹子！',
		'PandaLandCodes_No_Product_In_Land': '没有物品在搜索范围内！',
		'PandaLandCodes_Update_Panda_Attr_Fail': '更新用户属性失败！',
		'PandaLandCodes_Update_Land_Assets_Fail': '更新用户资产失败',
		'PandaLandCodes_Back_Assets_Carry_Fail': '带回来的商品失败！',
		'PandaLandCodes_Back_Assets_Carry_Empty': '主人, 呜喏没搜索到任何商品哈!',
		'PandaLandCodes_Delete_Back_Assets_Fail': '删除回归商品失败！',
		'PandaLandCodes_Panda_Out_Succ': '呜喏外出搜索成功！',
		'PandaLandCodes_Panda_Not_Sold': '呜喏并非出售',
		'PandaLandCodes_Sell_Panda_Succ': '出售呜喏成功！',
		'PandaLandCodes_Unsell_Panda_Succ': '取消出售呜喏成功！',
		'PandaLandCodes_Only_One_Unsold_Panda': '必须保留一只没出售的呜喏!',
		'PandaLandCodes_Buy_Panda_Fail': '购买呜喏失败',
		'PandaLandCodes_Buy_Panda_Succ': '购买呜喏成功',
		'PandaLandCodes_Back_Assets_Carry_Succ': '呜喏带回商品成功!',
		'PandaLandCodes_Drop_Panda_Fail': '呜喏丢弃失败!',
		'PandaLandCodes_Panda_Sire_Succ': '呜喏孵化成功',
		'Exchange_Product_Info_Not_Null': '商品兑换信息不能为空',
		'JoiCodes_Addr_Illegal': '地址格式不正确',
		'JoiCodes_Gen_Illegal': '基因格式不正确',
		'JoiCodes_Attr_Illegal': '属性格式不正确',
		'JoiCodes_Price_Illegal': '价格格式不正确',
		'JoiCodes_Email_Illegal': '邮件格式不正确',
		'JoiCodes_Pwd_Illegal': '密码格式不正确',
		'JoiCodes_State_Illegal': '状态格式不正确',
		'JoiCodes_Titude_Illegal': '经纬度格式不正确',
		'JoiCodes_ProductAttr_Illegal': '商品属性格式不正确',
		'JoiCodes_Dir_Illegal': '方向格式不正确',
		'JoiCodes_ProductId_Illegal': '商品id格式不正确',
		'JoiCodes_Phone_Illegal': '电话格式不正确',
		'Insufficient_Bamboo_Balance': '竹子余额不足',
		'Information_Not_Completed': '信息未填完！',
		'LandProductCodes_Roll_Out_Succ': '提现订单提交成功！',
		'Recharge_Info_Not_Null': '充值信息不为空',
		'Recharge_Assets_Succ': '资产充值订单发起成功！',
		'At_Least_50_Bamboo_For_Out': '外出至少需要50个竹子！',
		'Vote_Experied': '本此投票未开始或者已经过期！'
	}
}

module.exports = {
	statusCodes: statusCodes
}